import os
import io
import psycopg2
from dotenv import load_dotenv

load_dotenv()

# Source connection
LOCAL_HOST = os.getenv('DATABASE_HOST', 'localhost')
LOCAL_DB = os.getenv('DATABASE_NAME', 'kaveri')
LOCAL_USER = os.getenv('DATABASE_USER', 'postgres')
LOCAL_PW = os.getenv('DATABASE_PASSWORD', '98Teja66#')
LOCAL_PORT = 5432

# Destination connection
SUPABASE_HOST = 'db.ujdvgekijdpzelsebald.supabase.co'
SUPABASE_DB = 'postgres'
SUPABASE_USER = 'postgres'
SUPABASE_PW = os.environ.get('SUPABASE_PASSWORD')
SUPABASE_PORT = 5432

if not SUPABASE_PW:
    raise ValueError('SUPABASE_PASSWORD environment variable is required.')

print('=== CONNECTING TO DATABASES ===')
local_conn = psycopg2.connect(
    dbname=LOCAL_DB,
    user=LOCAL_USER,
    password=LOCAL_PW,
    host=LOCAL_HOST,
    port=LOCAL_PORT
)
print(' [OK] Connected to local database (kaveri)')

sb_conn = psycopg2.connect(
    dbname=SUPABASE_DB,
    user=SUPABASE_USER,
    password=SUPABASE_PW,
    host=SUPABASE_HOST,
    port=SUPABASE_PORT
)
sb_conn.autocommit = False
print(' [OK] Connected to Supabase PostgreSQL database')

local_cur = local_conn.cursor()
sb_cur = sb_conn.cursor()

try:
    print('\n=== STEP 1: CLEANUP / PREPARATION IN SUPABASE ===')
    sb_cur.execute('CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;')
    sb_cur.execute('SET search_path TO public, extensions;')
    
    # Drop any partially created tables in public
    sb_cur.execute('''
        DROP MATERIALIZED VIEW IF EXISTS public.monthly_revenue CASCADE;
        DROP TABLE IF EXISTS public.refresh_tokens CASCADE;
        DROP TABLE IF EXISTS public.reviews CASCADE;
        DROP TABLE IF EXISTS public.payments CASCADE;
        DROP TABLE IF EXISTS public.bookings CASCADE;
        DROP TABLE IF EXISTS public.accounts CASCADE;
        DROP TABLE IF EXISTS public.guests CASCADE;
        DROP TABLE IF EXISTS public.rate_plans CASCADE;
        DROP TABLE IF EXISTS public.rooms CASCADE;
        DROP TABLE IF EXISTS public.properties CASCADE;
        DROP TABLE IF EXISTS public.room_types CASCADE;
        DROP TABLE IF EXISTS public.legacy_reservations CASCADE;
    ''')
    print(' [OK] Cleaned up existing public schema objects')

    print('\n=== STEP 2: CREATING FUNCTIONS ===')
    sb_cur.execute('''
        CREATE OR REPLACE FUNCTION public.check_booking_guest_capacity() 
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            max_occ smallint;
        BEGIN
            SELECT rt.max_occupancy INTO max_occ
            FROM public.rooms r
            JOIN public.room_types rt ON rt.room_type_id = r.room_type_id
            WHERE r.room_id = NEW.room_id;

            IF NEW.guests_count > max_occ THEN
                RAISE EXCEPTION 'guests_count (%) exceeds room max_occupancy (%)', NEW.guests_count, max_occ
                    USING ERRCODE = '23514';
            END IF;

            RETURN NEW;
        END;
        $$;
    ''')

    sb_cur.execute('''
        CREATE OR REPLACE FUNCTION public.check_review_booking_status() 
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            b_status varchar(32);
        BEGIN
            SELECT status INTO b_status
            FROM public.bookings
            WHERE booking_id = NEW.booking_id;

            IF b_status != 'checked_out' THEN
                RAISE EXCEPTION 'Reviews can only be written after check-out (current status: %)', b_status
                    USING ERRCODE = '23514';
            END IF;

            RETURN NEW;
        END;
        $$;
    ''')
    print(' [OK] Custom trigger functions created')

    print('\n=== STEP 3: CREATING EXACT SCHEMA TABLES ===')

    # 1. room_types
    sb_cur.execute('''
        CREATE TABLE public.room_types (
            room_type_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name character varying(64) NOT NULL,
            max_occupancy smallint NOT NULL,
            CONSTRAINT room_types_name_key UNIQUE (name)
        );
    ''')

    # 2. properties
    sb_cur.execute('''
        CREATE TABLE public.properties (
            property_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name character varying(128) NOT NULL,
            city character varying(64) NOT NULL,
            star_rating smallint NOT NULL,
            CONSTRAINT chk_property_star_rating CHECK (((star_rating >= 1) AND (star_rating <= 5)))
        );
    ''')

    # 3. rooms
    sb_cur.execute('''
        CREATE TABLE public.rooms (
            room_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id bigint NOT NULL REFERENCES public.properties(property_id) ON DELETE RESTRICT,
            room_number character varying(16) NOT NULL,
            room_type_id bigint NOT NULL REFERENCES public.room_types(room_type_id) ON DELETE RESTRICT,
            CONSTRAINT uq_room_number_per_property UNIQUE (property_id, room_number)
        );
    ''')

    # 4. rate_plans
    sb_cur.execute('''
        CREATE TABLE public.rate_plans (
            rate_plan_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id bigint NOT NULL REFERENCES public.properties(property_id) ON DELETE RESTRICT,
            room_type_id bigint NOT NULL REFERENCES public.room_types(room_type_id) ON DELETE RESTRICT,
            valid daterange NOT NULL,
            nightly_rate numeric(10,2) NOT NULL,
            CONSTRAINT chk_rate_plan_rate CHECK ((nightly_rate > (0)::numeric)),
            CONSTRAINT chk_rate_plan_valid CHECK ((NOT isempty(valid))),
            CONSTRAINT no_overlapping_rate_plans EXCLUDE USING gist (property_id WITH =, room_type_id WITH =, valid WITH &&)
        );
    ''')

    # 5. guests
    sb_cur.execute('''
        CREATE TABLE public.guests (
            guest_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name character varying(128) NOT NULL,
            email character varying(255) NOT NULL,
            guest_phone character varying(32),
            guest_city character varying(64)
        );
    ''')
    sb_cur.execute('CREATE UNIQUE INDEX uq_guests_email_lower ON public.guests USING btree (lower((email)::text));')

    # 6. accounts
    sb_cur.execute('''
        CREATE TABLE public.accounts (
            account_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            guest_id bigint UNIQUE REFERENCES public.guests(guest_id) ON DELETE RESTRICT,
            email character varying(255) NOT NULL,
            password_hash text NOT NULL,
            role character varying(32) NOT NULL,
            property_id bigint REFERENCES public.properties(property_id) ON DELETE RESTRICT,
            is_active boolean DEFAULT true NOT NULL,
            created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT chk_account_property_scope CHECK (((((role)::text = ANY ((ARRAY['staff'::character varying, 'manager'::character varying])::text[])) AND (property_id IS NOT NULL)) OR (((role)::text = ANY ((ARRAY['guest'::character varying, 'owner'::character varying])::text[])) AND (property_id IS NULL)))),
            CONSTRAINT chk_account_role CHECK (((role)::text = ANY ((ARRAY['guest'::character varying, 'staff'::character varying, 'manager'::character varying, 'owner'::character varying])::text[])))
        );
    ''')
    sb_cur.execute('CREATE UNIQUE INDEX uq_accounts_email_lower ON public.accounts USING btree (lower((email)::text));')

    # 7. bookings
    sb_cur.execute('''
        CREATE TABLE public.bookings (
            booking_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            guest_id bigint NOT NULL REFERENCES public.guests(guest_id) ON DELETE RESTRICT,
            room_id bigint NOT NULL REFERENCES public.rooms(room_id) ON DELETE RESTRICT,
            stay daterange NOT NULL,
            guests_count smallint NOT NULL,
            status character varying(32) NOT NULL,
            CONSTRAINT chk_booking_guest_count CHECK ((guests_count > 0)),
            CONSTRAINT chk_booking_status CHECK (((status)::text = ANY ((ARRAY['confirmed'::character varying, 'checked_in'::character varying, 'checked_out'::character varying, 'cancelled'::character varying, 'no_show'::character varying])::text[]))),
            CONSTRAINT chk_booking_stay CHECK ((NOT isempty(stay))),
            CONSTRAINT no_overlapping_room_bookings EXCLUDE USING gist (room_id WITH =, stay WITH &&) WHERE (((status)::text = ANY ((ARRAY['confirmed'::character varying, 'checked_in'::character varying, 'checked_out'::character varying])::text[])))
        );
    ''')
    sb_cur.execute('CREATE INDEX idx_bookings_guest_id ON public.bookings USING btree (guest_id);')

    # 8. payments
    sb_cur.execute('''
        CREATE TABLE public.payments (
            payment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            booking_id bigint NOT NULL REFERENCES public.bookings(booking_id) ON DELETE CASCADE,
            amount numeric(10,2) NOT NULL,
            method character varying(32) NOT NULL,
            paid_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
            idempotency_key character varying(128),
            CONSTRAINT chk_payment_amount CHECK ((amount > (0)::numeric))
        );
    ''')
    sb_cur.execute('CREATE UNIQUE INDEX uq_payments_idempotency_key ON public.payments USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);')

    # 9. reviews
    sb_cur.execute('''
        CREATE TABLE public.reviews (
            review_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            booking_id bigint NOT NULL UNIQUE REFERENCES public.bookings(booking_id) ON DELETE CASCADE,
            rating smallint NOT NULL,
            review_text character varying(1000),
            reviewed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT chk_review_rating CHECK (((rating >= 1) AND (rating <= 5)))
        );
    ''')

    # 10. refresh_tokens
    sb_cur.execute('''
        CREATE TABLE public.refresh_tokens (
            refresh_token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            account_id bigint NOT NULL REFERENCES public.accounts(account_id) ON DELETE CASCADE,
            token_hash text NOT NULL UNIQUE,
            expires_at timestamp with time zone NOT NULL,
            created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
            revoked_at timestamp with time zone
        );
    ''')

    # 11. legacy_reservations
    sb_cur.execute('''
        CREATE TABLE public.legacy_reservations (
            row_id text,
            guest_name text,
            guest_email text,
            guest_phone text,
            guest_city text,
            hotel_name text,
            hotel_city text,
            hotel_star text,
            room_numbers text,
            room_type text,
            guests_count text,
            checkin text,
            checkout text,
            nightly_rate text,
            total_paid text,
            payment_method text,
            status text,
            notes text
        );
    ''')

    # Triggers
    sb_cur.execute('''
        CREATE TRIGGER trg_booking_guest_capacity 
        BEFORE INSERT OR UPDATE OF room_id, guests_count ON public.bookings 
        FOR EACH ROW EXECUTE FUNCTION public.check_booking_guest_capacity();

        CREATE TRIGGER trg_review_booking_status 
        BEFORE INSERT OR UPDATE OF booking_id ON public.reviews 
        FOR EACH ROW EXECUTE FUNCTION public.check_review_booking_status();
    ''')

    print(' [OK] Exact table structures and triggers created')

    print('\n=== STEP 4: MIGRATING DATA IN DEPENDENCY ORDER ===')
    migration_tables = [
        'room_types',
        'properties',
        'rooms',
        'rate_plans',
        'guests',
        'accounts',
        'bookings',
        'payments',
        'reviews',
        'refresh_tokens',
        'legacy_reservations',
    ]

    for table in migration_tables:
        print(f'Migrating table: {table:<25} ... ', end='', flush=True)
        buf = io.StringIO()
        local_cur.copy_expert(f'COPY public."{table}" TO STDOUT WITH (FORMAT csv, HEADER true);', buf)
        buf.seek(0)
        
        sb_cur.copy_expert(f'COPY public."{table}" FROM STDIN WITH (FORMAT csv, HEADER true);', buf)
        
        sb_cur.execute(f'SELECT COUNT(*) FROM public."{table}";')
        sb_cnt = sb_cur.fetchone()[0]
        local_cur.execute(f'SELECT COUNT(*) FROM public."{table}";')
        loc_cnt = local_cur.fetchone()[0]
        
        assert sb_cnt == loc_cnt, f'Mismatch in {table}: Local={loc_cnt}, Supabase={sb_cnt}'
        print(f'[OK] {sb_cnt} rows migrated')

    print('\n=== STEP 5: CREATING MATERIALIZED VIEW ===')
    sb_cur.execute('''
        CREATE MATERIALIZED VIEW public.monthly_revenue AS
        SELECT
            r.property_id,
            date_trunc('month'::text, (d.day)::timestamp with time zone) AS month,
            sum((
                SELECT rp.nightly_rate
                FROM public.rate_plans rp
                WHERE ((rp.property_id = r.property_id) AND (rp.room_type_id = r.room_type_id) AND (rp.valid @> (d.day)::date))
                ORDER BY lower(rp.valid) DESC
                LIMIT 1
            )) AS total_revenue
        FROM (public.bookings b
            JOIN public.rooms r ON ((r.room_id = b.room_id))
            CROSS JOIN LATERAL generate_series(lower(b.stay), (upper(b.stay) - 1), '1 day'::interval) d(day))
        WHERE ((b.status)::text = ANY ((ARRAY['confirmed'::character varying, 'checked_in'::character varying, 'checked_out'::character varying])::text[]))
        GROUP BY r.property_id, (date_trunc('month'::text, (d.day)::timestamp with time zone));
    ''')
    sb_cur.execute('REFRESH MATERIALIZED VIEW public.monthly_revenue;')
    print(' [OK] Materialized view monthly_revenue created and refreshed')

    print('\n=== STEP 6: SYNCHRONIZING SEQUENCES ===')
    seq_mappings = [
        ('accounts_account_id_seq', 'accounts', 'account_id'),
        ('bookings_booking_id_seq', 'bookings', 'booking_id'),
        ('guests_guest_id_seq', 'guests', 'guest_id'),
        ('payments_payment_id_seq', 'payments', 'payment_id'),
        ('properties_property_id_seq', 'properties', 'property_id'),
        ('rate_plans_rate_plan_id_seq', 'rate_plans', 'rate_plan_id'),
        ('refresh_tokens_refresh_token_id_seq', 'refresh_tokens', 'refresh_token_id'),
        ('reviews_review_id_seq', 'reviews', 'review_id'),
        ('room_types_room_type_id_seq', 'room_types', 'room_type_id'),
        ('rooms_room_id_seq', 'rooms', 'room_id'),
    ]

    for seq_name, tbl_name, col_name in seq_mappings:
        local_cur.execute(f'SELECT last_value, is_called FROM public."{seq_name}";')
        loc_val, loc_called = local_cur.fetchone()
        
        sb_cur.execute(f'SELECT COALESCE(MAX({col_name}), 1) FROM public."{tbl_name}";')
        max_col_val = sb_cur.fetchone()[0]
        target_val = max(loc_val, max_col_val)
        
        sb_cur.execute(f"SELECT setval('public.{seq_name}', {target_val}, true);")
        print(f' [OK] Sequence {seq_name:<38} synchronized to {target_val}')

    # Commit all changes to Supabase
    sb_conn.commit()
    print('\n======================================================')
    print('>>> ALL DATA AND SCHEMA COMMITTED TO SUPABASE POSTGRESQL! <<<')
    print('======================================================')

except Exception as e:
    sb_conn.rollback()
    print(f'\n[ERROR] Migration error: {e}')
    raise

finally:
    local_cur.close()
    local_conn.close()
    sb_cur.close()
    sb_conn.close()
